<#
Usage:
  - Place a token with Issues write access in `$env:GITHUB_TOKEN`.
  - Dry-run (default): `.































































































Write-Host "Done. Rerun with -Post to actually create items (requires valid token and repo access)." -ForegroundColor Cyan}  Write-Host "Prepared issue: $($p.title)" -ForegroundColor Green  Invoke-Api -Method Post -Url "$base/issues" -Body $payload | Out-Null  $payload = @{ title = $p.title; body = $p.body; labels = $p.labels; milestone = $milestoneNumber }foreach ($p in $parsed) {# 5) Create issues (or dry-run print)$milestoneNumber = ($msList | Where-Object { $_.title -eq 'Backlog v1.0' }).number$msList = try { Invoke-RestMethod -Uri "$base/milestones?state=open" -Headers $headers -Method Get -ErrorAction Stop } catch { @() }# 4) Find milestone number (if any)}  $parsed += @{ title = $title; body = $body; labels = $labels }  if (-not $labels) { $labels = @('backlog') }  $labels = ($b -split "`n") | Where-Object { $_ -match '^Labels:' } | ForEach-Object { ($_ -replace '^Labels:\s*','').Trim() } | ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }  } else { $body = '' }    $body = ($bodyLines -join "`n").Trim()    }      ($b -split "`n")[($bodyIndex+1)..($b -split "`n").Length]    } else {      ($b -split "`n")[($bodyIndex+1)..( ($b -split "`n").IndexOf($labelsLine) - 1 )]    $bodyLines = if ($labelsLine) {    $labelsLine = ($b -split "`n") | Where-Object { $_ -match '^Labels:' } | Select-Object -First 1    $bodyIndex = ($b -split "`n").IndexOf($bodyStart.ToString())  if ($bodyStart) {  $bodyStart = ($b -split "`n") | Select-String -Pattern '^Body:' -List | Select-Object -First 1  # Body is lines after 'Body:' until 'Labels:' or end  $title = ($titleLine -replace '^Title:\s*','').Trim()  if (-not $titleLine) { continue }  $titleLine = ($b -split "`n") | Where-Object { $_ -match '^Title:' } | Select-Object -First 1  # First line '##' or title; look for 'Title: ' lineforeach ($b in $blocks) {$parsed = @()$blocks = $issuesText -split "(?m)^---\s*$" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }# Simple parser: split by '---' blocks$issuesText = Get-Content $issueFile -Raw$issueFile = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Definition) '..\docs\BACKLOG_ISSUES.md'# 3) Read prepared issues file}  else { Invoke-Api -Method Post -Url "$base/labels" -Body $lab | Out-Null; Write-Host "Label prepared: $($lab.name)" }  if ($existing.name -contains $lab.name) { Write-Host "Label exists: $($lab.name)" }foreach ($lab in $labelsToEnsure) {$existing = try { Invoke-RestMethod -Uri "$base/labels" -Headers $headers -Method Get -ErrorAction Stop } catch { @() })  @{ name = 'backlog'; color = 'd4c5f9'; description = 'Backlog item' }  @{ name = 'task'; color = '1d76db'; description = 'Work item / task' },  @{ name = 'epic'; color = '0e8a16'; description = 'High level epic' },$labelsToEnsure = @(# 2) Ensure labels exist}  Write-Host "Milestone exists: $($ms.title)" -ForegroundColor Green} else {  Write-Host "Milestone prepared (or would be created in Post mode)." -ForegroundColor Green  Invoke-Api -Method Post -Url "$base/milestones" -Body $mBody | Out-Null  $mBody = @{ title = 'Backlog v1.0'; state = 'open'; description = "Imported from docs/BACKLOG.md on $(Get-Date -Format o)" }if (-not $ms) {$ms = $milestones | Where-Object { $_.title -eq 'Backlog v1.0' }$milestones = try { Invoke-RestMethod -Uri "$base/milestones?state=open" -Headers $headers -Method Get -ErrorAction Stop } catch { @() }# 1) Create milestone if not exists (open)}  }    return $null    if ($json) { Write-Host $json }    Write-Host "DRY RUN: $Method $Url" -ForegroundColor Cyan  } else {    return Invoke-RestMethod -Uri $Url -Method $Method -Headers $headers -Body $json -ErrorAction Stop  if ($Post) {  $json = if ($Body) { $Body | ConvertTo-Json -Depth 5 } else { $null }function Invoke-Api([string]$Method, [string]$Url, $Body) {}  Write-Host "No GITHUB_TOKEN found in environment. Export token and re-run. Ex: $env:GITHUB_TOKEN = '<token>'" -ForegroundColor Yellowif (-not $env:GITHUB_TOKEN) {$headers = @{ Authorization = "token $env:GITHUB_TOKEN"; 'User-Agent' = 'repo-agent'; 'Accept' = 'application/vnd.github+json' }$base  = "https://api.github.com/repos/$owner/$repo"$repo  = 'Autonomous-Trading-Agent'$owner = 'SamitDharia'# Configuration)  [switch]$Postparam(#>This script will create a milestone "Backlog v1.0", ensure labels `epic`, `task`, and `backlog` exist, then create the issues listed in `docs/BACKLOG_ISSUES.md`.  - To actually post: `.
eate_github_issues.ps1 -Post`eate_github_issues.ps1 -WhatIf` or run without `-Post`.